# Starter pipeline
trigger:
- main

pool: 
  vmImage: windows-latest

steps:
- script: echo 'Hello, world! projectJsonPath - $(Build.SourcesDirectory) outputPath - $(Build.ArtifactStagingDirectory)\Output '
  displayName: 'Run a one-line script'

- task: UiPathInstallPlatform@4
  inputs:
    cliVersion: 'WIN_23.10.8753.32995'
    cliNupkgPath: 

- task: UiPathAssets@4
  inputs:
    orchestratorConnection: 'OrchestratorDevOpsConnection'
    folderName: 'sandbox/Phil Harris'
    assetActionType: 'Deploy'
#    csvFile: 'OrchestratorAssets'
    
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#- task: UiPathPack@4
#  inputs:
#    versionType: 'CurrentVersion'
#    projectJsonPath: '$(Build.SourcesDirectory)'
#    outputType: 'Tests'
#    orchestratorConnection: 'OrchestratorDevOpsConnection'
#    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
#    traceLevel: 'Information'
  
- task: CmdLine@2
  displayName: 'List files'
  inputs:
    script: |
      for %%f in ( "$(Build.SourcesDirectory)\*" ) do @echo %%f

#- task: UiPathTest@4
#  continueOnError: true
#  inputs:
#    testTarget: 'TestProject'
#    testProjectPath: '$(Build.SourcesDirectory)' # Required only when testTarget = TestProject
#    orchestratorConnection: 'OrchestratorDevOpsConnection'
#    folderName: 'sandbox/Phil Harris'
#    traceLevel: 'Information'

- task: UiPathTest@4
  continueOnError: true
  inputs:
    testTarget: 'TestSet'
    testSet: 'Create_SAP_JournalEntry_DocumentReversal'
    orchestratorConnection: 'OrchestratorDevOpsConnection'
    folderName: 'sandbox/Phil Harris'
    traceLevel: 'Information'
    
- task: PublishBuildArtifacts@1
  continueOnError: true
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'BuildPipelineArtifact'
    publishLocation: 'Container'

