# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    orchestratorConnection: 'OrchestratorDevOpsConnection'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'OrchestratorDevOpsConnection'
    packagesPath: '$(Build_ArtifactStagingDirectory)\Output'
    folderName: 'sandbox/Phil Harris'
- main

pool:
  vmImage: windows-latest

steps:

